version: 2
updates:
  # Monitor Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(deps)"
    reviewers:
      - "jeffh"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        applies-to: version-updates
        cooldown:
          duration: 7

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    reviewers:
      - "jeffh"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        applies-to: version-updates
        cooldown:
          duration: 7
